### ISSUE TITLE
Remove HTTPHeaderDict.from_httplib

### ISSUE THREAD

**Issue by pquentin** [python-trio/urllib3#109]
We're not using httplib (the old name for http.client), so all mentions of `from_httplib` can be removed from the code.

This is a good first issue! If you're interested, please ask for help here.

**Comment by jab** [comment]
Hey @pquentin, thanks for tagging this "good first issue"! I just submitted #112 after successfully testing `tox -e py27-nobrotli` with those changes locally. Please let me know if I've missed something, and thanks for the great work bleaching urllib3!

**Comment by pquentin** [comment]
@jab Thank you for the pull request, and thank you for the kind words! I should be able to look at this today (in the next 12 hours).
