### ISSUE TITLE
Move urllib3 into src/urllib3

### ISSUE THREAD

**Issue by njsmith** [python-trio/urllib3#29]
I think we have to do this if we want to get tox working, because of these issues: https://docs.pytest.org/en/latest/goodpractices.html#choosing-a-test-layout-import-rules

And, weirdly... it might actually help with our problems with git having trouble figuring out the diff, because right now git is convinced that e.g. the new `urllib3/_async/connectionpool.py` can't be the same as the old `urllib3/connectionpool.py`, even though their contents are almost identical, because our branch still has a file called `urllib3/connectionpool.py` (and who cares that it's completely different from the old `urllib3/connectionpool.py`). But if we rename `urllib3/` → `src/urllib3/`, then git will fall back on looking at content to try to match up files, and should decide that `urllib3/connectionpool.py` matches `src/urllib3/_async/connectionpool.py`, instead of `src/urllib3/connectionpool.py`.

At least... I hope that's true?

**Comment by oliland** [comment]
+1
